#!/usr/bin/env python
import sys, os


import ROOT as r 
r.gSystem.Load('build/libHYDRA')
sys.path.append(os.getcwd()+'/python')

from traitlets.config import Config
c = Config()


c.InteractiveShellApp.exec_lines = [
    'import sys, os\n'
    'import ROOT as r\n',
    'r.gSystem.Load(\"build/libHYDRA\")\n'
    'from python.hydra import *\n',
    'Hydra.WelcomeMessage()\n',
]
if ( len(sys.argv) == 1 ): c.InteractiveShellApp.exec_lines.append('printc(\"Please set decay with SetDecay(decay)\"\n)')

c.InteractiveShellApp.exec_files = [
    'python/hydra.py',
]
c.InteractiveShell.colors = 'LightBG'
c.InteractiveShell.confirm_exit = False
c.TerminalIPythonApp.display_banner = False



import IPython
IPython.start_ipython(config=c)